version: "2"
run:
  tests: true
linters:
  enable:
    - gosec
    - misspell
  settings:
    gosec:
      excludes:
        - G204
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/razmser/gwt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
